import { motion, AnimatePresence } from "framer-motion";
import { ScrollArea } from "./ui/scroll-area";
import { Badge } from "./ui/badge";
import { Separator } from "./ui/separator";
import { Loader2, Terminal, Brain, HeartHandshake } from "lucide-react";
import { LogEntry } from '../types';
import { useGameStore } from '../state/gameStore';
import { useEffect, useRef } from 'react';
import { useReducedMotion } from '../hooks/useReducedMotion';
import { cn } from "../utils";
import { THEME } from "../theme";

// Speaker colors for better distinction
const speakerColors: Record<string, { bg: string, text: string, border: string }> = {
  'Subject 84': { bg: 'bg-[#292524]', text: 'text-[#e7e5e4]', border: 'border-[#44403c]' },
  'You': { bg: 'bg-[#292524]', text: 'text-[#e7e5e4]', border: 'border-[#44403c]' },
  'Magistra Selene': { bg: 'bg-[#7f1d1d]/10', text: 'text-[#fecaca]', border: 'border-[#991b1b]/30' },
  'Selene': { bg: 'bg-[#7f1d1d]/10', text: 'text-[#fecaca]', border: 'border-[#991b1b]/30' },
  'Provost': { bg: 'bg-[#7f1d1d]/10', text: 'text-[#fecaca]', border: 'border-[#991b1b]/30' },
  'Inquisitor Petra': { bg: 'bg-[#064e3b]/10', text: 'text-[#86efac]', border: 'border-[#065f46]/30' },
  'Petra': { bg: 'bg-[#064e3b]/10', text: 'text-[#86efac]', border: 'border-[#065f46]/30' },
  'Narrator': { bg: 'bg-transparent', text: 'text-[#a8a29e]', border: 'border-transparent' },
  'default': { bg: 'bg-[#1c1917]', text: 'text-[#d6d3d1]', border: 'border-[#292524]' }
};

export default function NarrativeLog() {
  const logs = useGameStore(s => s.logs);
  const isThinking = useGameStore(s => s.isThinking);
  const multimodalTimeline = useGameStore(s => s.multimodalTimeline);

  const viewportRef = useRef<HTMLDivElement>(null);
  const prefersReduced = useReducedMotion();

  useEffect(() => {
    if (viewportRef.current) {
        viewportRef.current.scrollTo({ top: viewportRef.current.scrollHeight, behavior: 'smooth' });
    }
  }, [logs.length, isThinking]);

  const renderLogContent = (log: LogEntry) => {
    const state = useGameStore.getState();
    const traumaLevel = state.gameState?.ledger?.traumaLevel ?? 0; 
    const isPsychosis = log.type === 'psychosis' || (log.type === 'narrative' && traumaLevel > 80);
    const logId = log.id; 
    
    // Check if there is a structured script associated with this log ID (via turn ID logic)
    // Note: Log ID usually matches Turn ID for narrative entries generated by Unified Director
    const multimodalTurn = multimodalTimeline.find(t => t.id === logId || (log.id.startsWith('narrative-') && t.text === log.content));
    
    const logScript = log.type === 'narrative' ? log.script : undefined;
    
    const hasScript = (log.type === 'narrative' && multimodalTurn?.script && multimodalTurn.script.length > 0) || (logScript && logScript.length > 0);
    
    // Prefer script from log object if available (legacy fallback) or from multimodal turn
    const script = multimodalTurn?.script || logScript;

    return (
      <div className="space-y-4">
        {/* Main Narrative Text */}
        {log.content && (
           <p className={cn(
             "text-lg md:text-xl leading-relaxed font-light font-serif",
             isPsychosis ? "text-[#fca5a5] italic animate-pulse" : "text-[#e7e5e4]"
           )}>
             {log.content}
           </p>
        )}

        {/* Dialogue Script */}
        {hasScript && script && (
          <div className="mt-6 space-y-3 pl-4 border-l-2 border-[#292524] py-2">
            {script.map((line, idx) => {
              const speakerKey = Object.keys(speakerColors).find(k => line.speaker.includes(k)) || 'default';
              const style = speakerColors[speakerKey];
              
              if (line.speaker === 'Narrator') {
                  return (
                      <p key={idx} className="text-sm text-[#a8a29e] italic pl-2">
                          {line.text}
                      </p>
                  );
              }

              return (
                <div key={idx} className={cn("flex flex-col gap-1 p-3 rounded-md border", style.bg, style.border)}>
                  <span className={cn("text-xs font-mono uppercase tracking-widest opacity-70", style.text)}>
                    {line.speaker}
                  </span>
                  <p className={cn("text-base font-serif leading-snug", style.text)}>
                    "{line.text}"
                  </p>
                  {line.emotion && (
                      <span className="text-[10px] text-[#a8a29e] italic">
                          ({line.emotion})
                      </span>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </div>
    );
  };

  return (
    <ScrollArea className="h-full" viewportRef={viewportRef}>
      <div className="p-6 md:p-10 space-y-12 text-[#e7e5e4]/90">
        <AnimatePresence initial={false}>
          {logs.map((log) => (
            <motion.div
              key={log.id}
              initial={prefersReduced ? false : { opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: prefersReduced ? 0 : 0.5 }}
              className="space-y-4"
            >
              {/* Log Type Indicator */}
              {log.type === 'system' && (
                  <div className={cn(
                      "flex items-center gap-2 font-mono text-xs uppercase tracking-widest border-b pb-2 mb-2",
                      log.content.includes("MEMORY") ? "text-[#a78bfa] border-[#7c3aed]/30" : 
                      log.content.includes("RELATIONSHIP") ? "text-[#f472b6] border-[#db2777]/30" : 
                      "text-[#a8a29e] border-[#292524]"
                  )}>
                      {log.content.includes("MEMORY") ? <Brain size={12} /> : 
                       log.content.includes("RELATIONSHIP") ? <HeartHandshake size={12} /> : 
                       <Terminal size={12} />}
                      {log.content.includes("MEMORY") ? "MEMORY ENGRAM" : 
                       log.content.includes("RELATIONSHIP") ? "SOCIAL DYNAMICS" : 
                       "SYSTEM LOG"}
                  </div>
              )}
              {log.type === 'thought' && (
                  <div className="bg-[#1c1917] p-4 rounded text-xs font-mono text-[#065f46] overflow-x-auto whitespace-pre-wrap border border-[#064e3b]/30">
                      {log.content}
                  </div>
              )}
              
              {(log.type === 'narrative' || log.type === 'psychosis') && renderLogContent(log)}

              {log.type === 'system' && (
                  <p className={cn(
                      "font-mono text-xs",
                      log.content.includes("MEMORY") ? "text-[#a78bfa]" : 
                      log.content.includes("RELATIONSHIP") ? "text-[#f472b6]" : 
                      "text-[#a8a29e]"
                  )}>{log.content}</p>
              )}

              <Separator className="bg-[#292524]/50 mt-8" />
            </motion.div>
          ))}
        </AnimatePresence>

        {isThinking && (
          <motion.div 
            initial={{ opacity: 0 }} 
            animate={{ opacity: 1 }} 
            className="flex items-center gap-4 text-[#065f46] py-8 justify-center"
          >
            <Loader2 className="animate-spin" size={24} />
            <span className="font-mono text-xs uppercase tracking-[0.2em] animate-pulse">
                Constructing Reality...
            </span>
          </motion.div>
        )}
      </div>
    </ScrollArea>
  );
}